version: '3'
services:
  web:
    container_name: py_amazonRestockBot
    build:
      context: ./python
      dockerfile: ./Dockerfile
    ports:
      - 8001:80
    volumes:
      - "./:/usr/src/app" #コンテナ内にディレクトリをマウント
  
  db:
    build:
      context: ./db
      dockerfile: ./Dockerfile
    container_name: db_amazonRestockBot
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      PGPASSWORD: admin
      POSTGRES_DB: amazonRestockBot
      TZ: "Asia/Tokyo"
    ports:
      - 5433:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data




